### ISSUE TITLE
bumpVersion replaces all the versions in package.json file, not just the "version":

### ISSUE THREAD

**Issue by shrutipatankar** [peritus/bumpversion#174]
When I set up bumpVersion to update package.json file, it updates every entry with the current "version": "major.minor.patch"

For example, if I have dependencies in package.json with the same version number as "version": "major.minor.patch", bumpVersion will update all.

For example (package.json):

**"version": "v1.0.0",**
"dependencies": {
    **"xyz": "^1.0.0",**
}

then running bumpVersion patch will make the file appear:
**"version": "v1.0.1",**
"dependencies": {
    **"xyz": "^1.0.1",**
}

It is not desirable to see the other dependencies getting changed.

**Comment by peritus** [comment]
@shrutipatankar 

If you're using npm, please use `npm version`: https://docs.npmjs.com/cli/version — it is much smarter and tailored to your environment.

If you need to use `bumpversion` because you need to update the version string in other places too (not just package.json), then have a look at the `search` and `replace` parameters and configuration, they can make sure only the right occurrence is replaced.

**Comment by shrutipatankar** [comment]
Thank you.
