### ISSUE TITLE
Auto-generate changelog

### ISSUE THREAD

**Issue by fizyk** [peritus/bumpversion#87]
Hey @peritus ,

I wonder, if automatic changelog generating would be within a scope of bumpversion? I've got some rough code to do this, I could polish.

Idea is to in one command:
* update changelog and commit
* print out the changelog (for 3party systems, wiki, or ticket about preparing release or particular deployment)

Configuration would be based probably by defining regexps.

**Comment by tantale** [comment]
Hi @fizyk,

I don't think bumpversion should generate the change log, because this is a different subject which isn't relevant to versioning. In my own opinion, the change log should be generated in parallel with the documentation: maybe with a Sphinx extension (see: [changelog extension](https://bitbucket.org/zzzeek/changelog)).

In order to generate the change log, you need to:
* define rules (a small grammar) that developers should follow to have formatted commit messages (see, for example: [Angular JS – Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-git-commit-guidelines)),
* define a way to filter messages (select only relevant messages);
* define a change log format to layout your change log (using reStructuredText or Markdown together with a template engine: [jinja](http://jinja.pocoo.org/)).

JavaScript developers can use: [git-changelog](https://github.com/rafinskipg/git-changelog).

Long is the road…

**Comment by peritus** [comment]
@fizyk thanks for opening this issue

However, as @tantale outlined already (thanks for the great overview!), this is indeed outside of the scope of this project. While I'd love to have auto-generated changelogs for all of my projects, this is probably not the place for this to be implemented. bumpversion exists to bump version numbers, not more not less.

However, I'm open to accept ideas/concepts/pull requests/etc. that allow interaction with tools generating changelogs. Given that bumpversion knows about how to bump versions for the project, inspecting that information might be a useful property when generating changelogs.

**Comment by fizyk** [comment]
Hmmm... @peritus  you're right. Maybe i've just looked to broad at this. With ie pypi releases being triggered by tagged builds on travis, bumpversion does get a central point of each release ;) Though it could be more valuable to trigger a command just before bumping versions...

**Comment by rickstaa** [comment]
+1 on having the ability to execute a command before committing. I for example use [auto-changelog](https://github.com/CookPete/auto-changelog) to update my changelog. I now have to do the following steps:

1. Call bumpversion (While having specified that it doesn't create a tag.
2. Create the versioning tag myself.
3. Run auto-changelog.
4. Commit.

**Comment by fizyk** [comment]
@rickstaa take a look at that pull request to bumpversion's fork:

https://github.com/c4urself/bump2version/pull/101

Till it lands there I'm using my fork of a fork and install it from git
